name: sonarCloud Scan

on: 
    push:
        branches:
            - main
            - master

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm install

        - name: Run tests with coverage
          run: npm run test:coverage

        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v5.0.0
          with:
            args: >
              -Dsonar.organization=wispard1
          env: 
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        


        
